
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Mvc store/Dockerfile'
        tags: |
          $(tag)
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      rydhadockerhub
      /products-storeon-mvc:v2.$(Build.BuildId)
- task: CopyFiles@2
  inputs:
    Contents: |
      **
      mssql-config-map.yaml
      mssql-pv-azure.yaml
      mssql-secret.yaml
      mvc-deployment-azure.yaml
      product-mssql-deployemnt.yaml
      mvc-deployment.yaml
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
